version: '3.8'
services:
  app:
    build: .
    command: sleep infinity
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/playbackdb
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: playbackdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
