version: '3.8'
services:
  app:
    container_name: playback-api
    build: .
    command: sleep infinity
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user:password@db:5432/playbackdb
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: playbackdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
